config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Read all
  get '/tasks', to: 'tasks#index'
  # Create
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  # Update
  get '/tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch '/tasks/:id', to: 'tasks#update'
  # Destroy
  delete '/tasks/:id', to: 'tasks#destroy', as: :task_delete
  # Read one
  get '/tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
    @result = @task.completed ? 'This task is completed' : 'This task is not completed.'
  end

  def new
    # Why there are 2 Task.new?
    @task = Task.new
  end

  def create
    # @task = Task.new(params[:task])
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :new
    end
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  # To avoid the ActiveModel::ForbiddenAttributesError
  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Task Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;500;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit <%= @task.title %></h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<div class="container">

  <div class="headline">
    <div class="headline-info">
      <h1>Task Manager</h1>
      <%= link_to tasks_new_path do %>
        <p><i class="fa-regular fa-file"></i> Add a new task</p>
      <% end %>
    </div>
  </div>

  <ol>
    <% @tasks.each do |t| %>
      <% if t.completed %>
        <li>
          <div class="task-info">
            <div class="check-icon">
              <i class="fa-solid fa-circle-check"></i>
            </div>
              <%= link_to t.title, task_path(t) %>
          </div>
        </li>
      <% else %>
        <li>
          <div class="task-info">
            <div class="check-icon">
              <i class="fa-regular fa-circle"></i>
            </div>
              <%= link_to t.title, task_path(t) %>
          </div>
        </li>
      <% end %>
    <% end %>
  </ol>

</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div class="container">

  <div class="task-headline">
    <% if @task.completed %>
      <h1><i class="fa-solid fa-circle-check check-status"></i><%= @task.title %></h1>
    <% else %>
      <h1><i class="fa-regular fa-circle check-status"></i><%= @task.title %></h1>
    <% end %>
  </div>

  <h2>Task details</h2>
  <div class="task-content">
    <h3><%= @task.details %></h3>
  </div>

  <p>Mark task as completed</p>
  <%= form_with model: @task do |f| %>
    <%= f.check_box :completed %>
    <%= f.submit %>
  <% end %>

  <%= link_to "Edit task", task_edit_path(@task) %>

  <%= link_to "Delete",
    task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>

  <%= link_to "Back to list", tasks_path %>

</div>